### ISSUE TITLE
normalize() doesn't return the same as p5

### ISSUE THREAD

**Issue by zltn** [quinton-ashley/q5.js#10]
I've been testing the following [sketch](https://gist.github.com/zltn/567bc3f05419fcf50ed2dbe2fe4a8f45). I've debugged al the way until `normalize()` (line 80), which results in a `NaN`. If I comment out the normalize it starts working for a couple of frames but runs in to more issues. 

Stopped debugging here but this might be a good test case to find some more discrepancies

**Comment by quinton-ashley** [comment]
@zltn thanks for the issue report! Fixed in v1.1.17
