### ISSUE TITLE
heading()

### ISSUE THREAD

**Issue by ormaq** [quinton-ashley/q5.js#8]
From the flocking p5 [example ](https://p5js.org/examples/simulate-flocking.html)

this.velocity = p.createVector(p.random(-1, 1), p.random(-1, 1));

 let theta = this.velocity.heading() + p.radians(90);
 
 
 Upon calling this code we get that $ is not defined
 
 you can fix this using 
 
```js
heading() {
		let $ = this;
		return Math.atan2($.y, $.x);
	}
```

but this is not a pretty solution * And does not really work*

**Comment by quinton-ashley** [comment]
hmm interesting I'll have to take a look at that

**Comment by quinton-ashley** [comment]
fixed this issue by providing the Vector constructor a reference to the p5 instance which it saves as a property `this._$` that way the cos, sin, tan, atan2 functions can all work and respect the p5 instance's `angleMode` setting :)

In v1.1.12 I also made the changes you requested on Discord. Good work on that! Let me know if you find any other compatibility issues.
